language: cpp
os:
  - osx
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - brew tap staticfloat/julia
  - brew update
  - brew install julia
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Accelerate")'
